apiVersion: v1
kind: Secret
metadata:
  name: ecomm-secrets-d-aks
type: Opaque # Indicates arbitrary user-defined data
data:
  # PostgreSQL Credentials (for all three DBs)
  POSTGRES_USER: "cG9zdGdyZXM=" # Base64 for 'postgres'
  POSTGRES_PASSWORD: "cG9zdGdyZXM=" # Base64 for 'postgres'

  # RabbitMQ Credentials
  RABBITMQ_USER: "Z3Vlc3Q=" # Base64 for 'guest'
  RABBITMQ_PASS: "Z3Vlc3Q=" # Base64 for 'guest'

  # Azure Storage Account Credentials for Product Service image uploads (from Week 03 Example 3)
  # REPLACE WITH YOUR ACTUAL BASE64 ENCODED VALUES
  # Example: 
  # for mac : echo -n 'myazurestorageaccount' | base64
  # for windows (in powershell): [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("your_storage_account_key_string"))
  AZURE_STORAGE_ACCOUNT_NAME: "c2l0NzIyc3RvcmFnZTEx"
  # Example: 
  # for mac : echo -n 'your_storage_account_key_string' | base64
  # for windows (in powershell): [System.Convert]::ToBase64String([System.Text.Encoding]::UTF8.GetBytes("your_storage_account_key_string"))
  AZURE_STORAGE_ACCOUNT_KEY: "WnlxSFV5dWpGWXhiZ3RweUJHcmh2VmQxSjFNNDd3b1p1OTNuN1lJWUxVNUQ4SzJHTGkrOHNMNUl4QXFsVHlHenJ5eHlIYWNwZ2g5cytBU3RwSnpVdWc9PQ=="