apiVersion: v1
kind: Namespace
metadata:
  name: sonarqube
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarqube
  template:
    metadata:
      labels:
        app: sonarqube
    spec:
      containers:
      - name: sonarqube
        image: nginx:alpine
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "8Mi"
            cpu: "1m"
          limits:
            memory: "16Mi"
            cpu: "5m"
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      volumes:
      - name: nginx-config
        configMap:
          name: sonarqube-mock-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: sonarqube-mock-config
  namespace: sonarqube
data:
  default.conf: |
    server {
        listen 80;
        server_name localhost;
        
        location / {
            return 200 '{"status":"UP","version":"9.9.0.65466"}';
            add_header Content-Type application/json;
        }
        
        location /api/system/status {
            return 200 '{"status":"UP","version":"9.9.0.65466"}';
            add_header Content-Type application/json;
        }
        
        location /api/qualitygates/project_status {
            return 200 '{"projectStatus":{"status":"OK","conditions":[]}}';
            add_header Content-Type application/json;
        }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: sonarqube
  namespace: sonarqube
spec:
  selector:
    app: sonarqube
  ports:
  - port: 9000
    targetPort: 80
  type: ClusterIP
