apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-staging
  namespace: staging
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend-container
        image: sit722devopsacr.azurecr.io/frontend:staging
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        env:
        - name: PRODUCT_API_BASE_URL
          value: http://product-service-staging:8000
        - name: ORDER_API_BASE_URL
          value: http://order-service-staging:8001
        - name: CUSTOMER_API_BASE_URL
          value: http://customer-service-staging:8002
        - name: ENVIRONMENT
          value: staging
        - name: VERSION
          value: "staging"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend-staging
  namespace: staging
  labels:
    app: frontend
spec:
  selector:
    app: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
