apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-service-staging
  namespace: staging
  labels:
    app: order-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: order-service
  template:
    metadata:
      labels:
        app: order-service
    spec:
      containers:
      - name: order-service-container
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: POSTGRES_HOST
          value: order-db-service-staging
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: ORDERS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: POSTGRES_PASSWORD
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: RABBITMQ_PASS
        - name: PRODUCT_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: PRODUCT_SERVICE_URL
        - name: CUSTOMER_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: CUSTOMER_SERVICE_URL
        - name: ENVIRONMENT
          value: staging
---
apiVersion: v1
kind: Service
metadata:
  name: order-service-staging
  namespace: staging
  labels:
    app: order-service
spec:
  selector:
    app: order-service
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 80
  type: LoadBalancer
