apiVersion: apps/v1
kind: Deployment
metadata:
  name: product-service-staging
  namespace: staging
  labels:
    app: product-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: product-service
  template:
    metadata:
      labels:
        app: product-service
    spec:
      containers:
      - name: product-service-container
        image: nginx:alpine
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 5
        env:
        - name: POSTGRES_HOST
          value: product-db-service-staging
        - name: POSTGRES_DB
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: PRODUCTS_DB_NAME
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: POSTGRES_PASSWORD
        - name: AZURE_STORAGE_ACCOUNT_NAME
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: AZURE_STORAGE_ACCOUNT_NAME
        - name: AZURE_STORAGE_ACCOUNT_KEY
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: AZURE_STORAGE_ACCOUNT_KEY
        - name: AZURE_STORAGE_CONTAINER_NAME
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: AZURE_STORAGE_CONTAINER_NAME
        - name: AZURE_SAS_TOKEN_EXPIRY_HOURS
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: AZURE_SAS_TOKEN_EXPIRY_HOURS
        - name: RABBITMQ_HOST
          valueFrom:
            configMapKeyRef:
              name: ecomm-config-staging
              key: RABBITMQ_HOST
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: RABBITMQ_USER
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: ecomm-secrets-d-aks
              key: RABBITMQ_PASS
        - name: ENVIRONMENT
          value: staging
---
apiVersion: v1
kind: Service
metadata:
  name: product-service-staging
  namespace: staging
  labels:
    app: product-service
spec:
  selector:
    app: product-service
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 80
  type: LoadBalancer
